name: Deploy

on:
  push:
    branches: [lunar]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy

    steps:
      - name: Checkout from GitHub
        uses: actions/checkout@master

      - name: Use JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws-region: us-east-2
          
      - name: Authenticate with CodeArtifact
        run: echo "CODEARTIFACT_TOKEN=`aws codeartifact get-authorization-token --domain lunarclient --domain-owner 556596233875 --query authorizationToken --output text`" >> $GITHUB_ENV

      - name: Build
        run: ./gradlew uploadArchives -PspongeRepo="https://lunarclient-556596233875.d.codeartifact.us-east-2.amazonaws.com/maven/lunarclient/" -PspongeUsername="aws" -PspongePassword=${CODEARTIFACT_TOKEN}
