name: Deploy

on:
  push:
    branches:
      - lunar
      - java-11

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    name: Deploy

    steps:
      - name: Checkout from GitHub
        uses: actions/checkout@master

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ARTIFACTS_ROLE_ARN }}
          aws-region: us-east-2

      - name: Use JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Build
        run: |
          export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain lunarclient --domain-owner 947665438472 --query authorizationToken --output text`
          ./gradlew publish -PspongeRepo="https://lunarclient-947665438472.d.codeartifact.us-east-2.amazonaws.com/maven/maven/" -PspongeUsername=aws -PspongePassword=${CODEARTIFACT_AUTH_TOKEN}
