name: Deploy

on:
  push:
    branches:
      - lunar
      - java-11
      - "merge/0.8.5+fabric"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy

    steps:
      - name: Checkout from GitHub
        uses: actions/checkout@master

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws-region: us-east-2

      - name: Use JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Build
        run: |
          export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain lunarclient --domain-owner 947665438472 --query authorizationToken --output text`
          ./gradlew publish -PspongeRepo="https://lunarclient-947665438472.d.codeartifact.us-east-2.amazonaws.com/maven/maven/" -PspongeUsername=aws -PspongePassword=${CODEARTIFACT_AUTH_TOKEN}
